### PR TITLE
string-manipulation-3

### PR DESCRIPTION
**Pull request by easton-morris**

### CODE REVIEW

**Comment by easton-morris** [comment]
image

**Comment by easton-morris** [comment]
just in case you get to it before I get back to this: check reverse words for a giggle lol

**Comment by easton-morris** [comment]
image

Just kidding I'm just rewriting it now.

**Comment by easton-morris** [comment]
image

fixed! I'm potentially hireable again lol

**Review by BrettAlbright — APPROVED** [review]
👍🏼

**Pull request merged**
